### PR TITLE
We now showing characters limit.

### PR DESCRIPTION
**Pull request by b0noI**
Looks like this:

Screenshot 2023-01-07 at 6 25 29 PM

### CODE REVIEW

**Comment by b0noI** [comment]
fix for #1

**Comment by kasavine** [comment]
1. Resolve conflicts.
2. Numbers should be inside the textarea box, grey numbers in the right bottom corner.
3. Limit 280?

**Comment by b0noI** [comment]
yep, 280: https://developer.twitter.com/en/docs/counting-characters

**Comment by b0noI** [comment]
an updated view on desktop and mobile:

Screenshot 2023-01-07 at 6 51 01 PM
Screenshot 2023-01-07 at 6 50 23 PM

**Comment by b0noI** [comment]
Color updated:

Screenshot 2023-01-07 at 6 54 58 PM

**Pull request merged**
